// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfBackend struct {
	Ipv4 uint32
	Mac  [6]uint8
}

type bpfFlow struct {
	Saddr uint32
	Smac  [6]uint8
	_     [2]byte
	Ports uint32
}

type bpfFlowKey struct {
	BackendAddr uint32
	Port        uint16
	Protocol    uint8
	_           [1]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	XdpDecap        *ebpf.ProgramSpec `ebpf:"xdp_decap"`
	XdpLoadbalancer *ebpf.ProgramSpec `ebpf:"xdp_loadbalancer"`
	XdpPass         *ebpf.ProgramSpec `ebpf:"xdp_pass"`
	XdpTest         *ebpf.ProgramSpec `ebpf:"xdp_test"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	BackendMap     *ebpf.MapSpec `ebpf:"backend_map"`
	EgressMetadata *ebpf.MapSpec `ebpf:"egress_metadata"`
	IpToIndexMap   *ebpf.MapSpec `ebpf:"ip_to_index_map"`
	LbMetadata     *ebpf.MapSpec `ebpf:"lb_metadata"`
	PacketFlowMap  *ebpf.MapSpec `ebpf:"packet_flow_map"`
	XdpStatsMap    *ebpf.MapSpec `ebpf:"xdp_stats_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	BackendMap     *ebpf.Map `ebpf:"backend_map"`
	EgressMetadata *ebpf.Map `ebpf:"egress_metadata"`
	IpToIndexMap   *ebpf.Map `ebpf:"ip_to_index_map"`
	LbMetadata     *ebpf.Map `ebpf:"lb_metadata"`
	PacketFlowMap  *ebpf.Map `ebpf:"packet_flow_map"`
	XdpStatsMap    *ebpf.Map `ebpf:"xdp_stats_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.BackendMap,
		m.EgressMetadata,
		m.IpToIndexMap,
		m.LbMetadata,
		m.PacketFlowMap,
		m.XdpStatsMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	XdpDecap        *ebpf.Program `ebpf:"xdp_decap"`
	XdpLoadbalancer *ebpf.Program `ebpf:"xdp_loadbalancer"`
	XdpPass         *ebpf.Program `ebpf:"xdp_pass"`
	XdpTest         *ebpf.Program `ebpf:"xdp_test"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.XdpDecap,
		p.XdpLoadbalancer,
		p.XdpPass,
		p.XdpTest,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
